services:
  - type: web
    name: chat-app
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
      cd ../backend
      npm install
    startCommand: cd backend && node index.js
    nodeVersion: 18.x
